### ISSUE TITLE
Feature request: action when no regexp is matched and invite restriction

### ISSUE THREAD

**Issue by toushin-taishi** [8go/matrix-eno-bot#14] opened 2021-03-24 05:18 UTC
Hi. Thanks so much for providing this BOT. I would like to know if the following are possible and if not, could you kindly treat it as a feature request?

1. Is there a command that will be triggered when no regexp matched? I would like the BOT to return:  " string " is an unrecognized command or something like that OR to just totally ignore the message.
2. Is it possible to specify the account or room that the BOT will accept invites from?

Thanks in advance!

**Comment by 8go** [comment] 2021-03-25 07:55
Hi @toushin-taishi 

Thank you for bringing up a few good points!

Regarding 1: 
If no regex matches then (internal) function _unknown_command() will be called. See
https://github.com/8go/matrix-eno-bot/blob/c67220057728988e035557709f333fb1f92b9cfc/bot_commands.py#L136

Basically, you will get a message saying "Try the `help` command for more information."

Regarding 2: 
No. There are currently no white-lists or black-lists for invites. Sorry. I will leave your issue open as a Feature Request. 
Maybe someone would like to contribute this whitelist/blacklist idea!

**Comment by toushin-taishi** [comment] 2021-03-29 02:04
Thanks for the reply. I'll check again the wild-card match, the last time I tried, it segfaults when there is no match found. Also, is there a way that the BOT will include or mention the matrix username or account on its reply?

**Comment by toushin-taishi** [comment] 2021-04-02 05:51
Hi, I don't know if it's a config error on my part or something. But when there is no matching regexp, I'm having the following error:
```
2021-04-02 13:44:56,203 | bot_commands [DEBUG] bot_commands :: Command.process: xx <nio.rooms.MatrixRoom object at 0x7fd9f5f66d00>
2021-04-02 13:44:56,231 | __main__ [DEBUG] Traceback (most recent call last):
  File "/opt/matrix-eno-bot/main.py", line 169, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/matrix-eno-bot/main.py", line 156, in main
    await client.sync_forever(timeout=30000, full_state=True)
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 1181, in sync_forever
    await self.run_response_callbacks([await response])
  File "/usr/lib/python3.8/asyncio/tasks.py", line 608, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 1028, in sync
    response = await self._send(
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 774, in _send
    await self.receive_response(resp)
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 689, in receive_response
    await self._handle_sync(response)
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 656, in _handle_sync
    await self._handle_joined_rooms(response)
  File "/usr/local/lib/python3.8/dist-packages/nio/client/async_client.py", line 583, in _handle_joined_rooms
    await asyncio.coroutine(cb.func)(room, event)
  File "/opt/matrix-eno-bot/callbacks.py", line 102, in message
    await command.process()
  File "/opt/matrix-eno-bot/bot_commands.py", line 84, in process
    elif self.command_dict.match(self.commandlower):
  File "/opt/matrix-eno-bot/command_dict.py", line 179, in match
    if len(cmd) > 0:
TypeError: object of type 'NoneType' has no len()
```
I had to workaround with including a wildcard match in hello's regex:
`regex:             "^salut$|^ciao$|^hallo$|^hi$|^servus$|^hola$|^hello$|^hello .*$|^bonjour$|^bonne nuit$|^hello.sh$|."`

Please advise on what to do, thanks! 
Also, as I said in my previous comment, is it possible to mention the account name that made the command on the bot's reply?

**Comment by 8go** [comment] 2021-04-07 12:32
Thank you @toushin-taishi 

Excellent, you found a small bug. It is fixed in 8ba6ac9c74c74f02405aeca6e86fc15cae449b79.

Please be so kind enough and set the regex of `hello` back as it was originally.
Then test again with the new code (1 line was changed). See 8ba6ac9c74c74f02405aeca6e86fc15cae449b79.

I expect that you bug is fixed now. 

Regarding: is it possible to mention the account name that made the command on the bot's reply?
The answer: No. Please open a separate issue specific to this, something like `provide ability to mention requesting account name in bot's reply` With a new issue, we can track this separately.

**Comment by toushin-taishi** [comment] 2021-04-08 01:51
Thank you very much @8go for the reply and the fix.

Another thing, In commands.yaml, line 288 and 312 has "|" in the end, causing wildcard matches:

288 regex:             "^otp$|^totp$|^otp .*$|^totp .*$|"
312 regex:             "^usr$|^user$|^users$|^users .*$|^users.sh$|"

removing the "|" in those lines triggers the function _unknown_command() when no match is found.

**Comment by 8go** [comment] 2021-04-18 11:19
Wow, thank you again @toushin-taishi 

You found another bug! Excellent. Well done!

Fixed in https://github.com/8go/matrix-eno-bot/commit/29b986d7cb4458850170ff0ffe0e6beb018ae347 

It is appreciated, it will help other people too. 

:+1: and :heart:

**Comment by 8go** [comment] 2021-04-18 11:24
@toushin-taishi 

Do me a favor, we try to track each "problem" separately in separate Github request. Here we are mixing 2 issues.

Could you please open a new github issue, for example entitled "Feature request: invite restriction"
with some text like 
```
Is it possible to specify the account or room that the BOT will accept invites from?
```

**Comment by 8go** [comment] 2021-08-05 18:34
Closing this because the bug has been fixed and the issue is now tracked under issue #20.

**Closed by 8go** 2021-08-05 18:34 UTC
